<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameTracker.Data\GameTracker.Data.csproj" />
    <ProjectReference Include="..\GameTracker.ViewModels\GameTracker.ViewModels.csproj" />
  </ItemGroup>

</Project>
